steps:
  # Step 0: Install Python dependencies
  - name: 'python:3.9'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
    id: 'install-dependencies'

  # Step 1: Train your model and upload it to a GCS bucket (example step)
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['train.py']
    id: 'train-model'
    secretEnv: ['BUCKET_NAME', 'BUCKET_ID']
    waitFor: ['install-dependencies']

  # Step 2: Deploy the model to an endpoint
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['deploy.py']
    waitFor: ['train-model']

# Define available secrets for the build
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/BUCKET_NAME/versions/latest
      env: 'BUCKET_NAME'
    - versionName: projects/$PROJECT_ID/secrets/BUCKET_ID/versions/latest
      env: 'BUCKET_ID'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "86400s"
